import { describe, it, expect } from 'vitest';
import index from '../rooms-index.json';
import { MERGED_ROOMS, mergeRoomGroups } from '../mergedRooms';
import type { RoomFeature, RoomIndexEntry, RoomsCollection } from '../../../types/campusMap';
import { pointInRing } from './pointInRing';

const INDEX = index as RoomIndexEntry[];

// One point strictly inside each original polygon, taken from reis-data's
// rooms-465899.geojson (shapely `representative_point`, 2026-09-24). If a merged
// outline ever stops covering one of these, a piece of the room fell off.
const MEMBER_POINTS: Record<string, [number, number]> = {
  BA25N1001: [16.6145765, 49.21045],
  BA25N1001A: [16.614469, 49.2104755],
  BA25N1001B: [16.6144963, 49.2104575],
  BA25N1001C: [16.6145006, 49.210426],
  BA25N1001D: [16.614547, 49.2104865],
  BA25N1002A: [16.614605, 49.210505],
  BA25N1002B: [16.6146468, 49.2105205],
  BA25N1002C: [16.61469, 49.210536],
  BA25N1002D: [16.6146769, 49.210485],
  BA25N1003A: [16.6147586, 49.210562],
  BA25N1003B: [16.6148298, 49.210578],
  BA25N1003C: [16.6147881, 49.2105265],
  BA25N1004: [16.6147571, 49.2104405],
  BA25N1004A: [16.614524, 49.2103925],
  BA25N1004B: [16.614556, 49.2103535],
};

const feature = (id: number, name: string): RoomFeature => ({
  type: 'Feature',
  geometry: { type: 'Polygon', coordinates: [[[16.6, 49.2]]] },
  properties: {
    id,
    buildingId: 465899,
    floorId: 475896,
    floorLevel: 1,
    name,
    nickname: null,
    type: 'office',
    category: 'office',
    label: 'Office',
    passportNumber: name,
    seats: null,
    hasProjector: false,
    hasWhiteboard: false,
    code: null,
  },
});

const allMembers = MERGED_ROOMS.flatMap((r) => r.members);
const buildingX = (): RoomsCollection => ({
  type: 'FeatureCollection',
  features: [
    feature(475905, 'BA25N1009'), // a toilet — a neighbour that must survive
    ...allMembers.map((name, i) => feature(476000 + i, name)),
  ],
});
const names = (c: RoomsCollection) =>
  c.features.map((f) => f.properties.nickname ?? f.properties.name);

describe('MERGED_ROOMS', () => {
  it('names the three IS classrooms, the study room and the shop', () => {
    expect(MERGED_ROOMS.map((r) => r.nickname)).toEqual([
      'X01',
      'X02',
      'X03',
      'Studovna X',
      'MENDELU Shop',
    ]);
  });

  it("keeps a real member as each room's identity, listed first", () => {
    for (const room of MERGED_ROOMS) expect(room.members[0]).toBe(room.name);
  });

  it('covers every piece it replaces', () => {
    for (const room of MERGED_ROOMS) {
      if (!room.ring) continue; // a relabel keeps the member's own outline
      for (const m of room.members) {
        const point = MEMBER_POINTS[m];
        expect(point, m).toBeDefined();
        expect(pointInRing(point!, room.ring), `${m} inside ${room.nickname}`).toBe(true);
      }
    }
  });

  it('draws each outline as a closed ring', () => {
    for (const room of MERGED_ROOMS) {
      if (!room.ring) continue;
      expect(room.ring.length).toBeGreaterThanOrEqual(4);
      expect(room.ring[0]).toEqual(room.ring[room.ring.length - 1]);
    }
  });

  it('never lets two groups claim the same piece', () => {
    expect(new Set(allMembers).size).toBe(allMembers.length);
  });
});

describe('mergeRoomGroups', () => {
  it('replaces each group with one room and leaves the neighbours alone', () => {
    const out = mergeRoomGroups(buildingX());
    expect(names(out)).toEqual(['BA25N1009', 'X01', 'X02', 'X03', 'Studovna X', 'MENDELU Shop']);
  });

  it('relabels the shop but keeps its own outline', () => {
    const before = buildingX();
    const own = before.features.find((f) => f.properties.name === 'BA25N1015')!.geometry;
    const shop = mergeRoomGroups(before).features.find((f) => f.properties.name === 'BA25N1015');
    expect(shop?.geometry).toBe(own);
    expect(shop?.properties).toMatchObject({ nickname: 'MENDELU Shop', category: 'other' });
  });

  it('gives the merged room the outline, and the building and floor of its pieces', () => {
    const x01 = mergeRoomGroups(buildingX()).features.find((f) => f.properties.nickname === 'X01');
    expect(x01?.geometry.coordinates[0]).toEqual(MERGED_ROOMS[0]!.ring);
    expect(x01?.properties).toMatchObject({
      id: MERGED_ROOMS[0]!.id,
      name: 'BA25N1001',
      buildingId: 465899,
      floorId: 475896,
      category: 'teaching',
    });
  });

  it('is a no-op on data that is already merged', () => {
    const once = mergeRoomGroups(buildingX());
    expect(mergeRoomGroups(once)).toBe(once);
  });

  it('returns other buildings untouched', () => {
    const other: RoomsCollection = {
      type: 'FeatureCollection',
      features: [feature(1, 'BA01N1052')],
    };
    expect(mergeRoomGroups(other)).toBe(other);
  });
});

// rooms-index.json is regenerated by reis-data's buildMapData.mjs, which knows
// nothing about these merges. If a regeneration brings the pieces back, search
// offers rooms the map no longer draws — fail here instead.
describe('rooms-index.json agrees with the merge', () => {
  it('has exactly one entry per merged room, pointing at its polygon', () => {
    for (const room of MERGED_ROOMS) {
      const hits = INDEX.filter((e) => e.placeId === room.id);
      expect(hits, room.nickname).toHaveLength(1);
      expect(hits[0]).toMatchObject({ code: room.name, nickname: room.nickname });
    }
  });

  it('no longer lists the pieces', () => {
    const kept = new Set(MERGED_ROOMS.map((r) => r.name));
    const stale = INDEX.filter((e) => allMembers.includes(e.code) && !kept.has(e.code));
    expect(stale.map((e) => e.code)).toEqual([]);
  });
});
