import type { Tutorial } from './types';

export const MOCK_TUTORIALS: Tutorial[] = [
  {
    id: 'mock-welcome-mendelu',
    associationId: 'supef',
    title: 'Welcome to Mendelu',
    description: 'Essential tips for new PEF students',
    isPublished: true,
    createdBy: 'admin@supef.cz',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
    slides: [
      {
        id: 'slide-1',
        tutorialId: 'mock-welcome-mendelu',
        order: 1,
        layout: 'two-column',
        leftIcon: 'hand',
        leftTitle: 'NA ZNAMENÍ = Request stop',
        leftContent: `- It means that the stop is only on request.\n- Wave when you see tram / bus arriving.\n- To get off press a button for your tram / bus to stop.\n- Some stops change to request stops at night or on weekends.`,
        rightIcon: 'ticket',
        rightTitle: 'Tickets',
        rightContent: `**Short term:**\n- You can buy them in **machines** at some stops, in **DPMB app** or use **Beep and Go system** (you tap your debit card on the validation machine when you enter the vehicle).\n- Paper tickets must be validated in the machine on board.`,
      },
      {
        id: 'slide-2',
        tutorialId: 'mock-welcome-mendelu',
        order: 2,
        layout: 'single',
        leftIcon: 'map-pin',
        leftTitle: 'Campus Locations',
        leftContent: `**Main Buildings:**\n- **Budova Q** - Main PEF building, lectures and seminars\n- **Knihovna** - University library, open until 10 PM\n- **Menza** - Canteen with affordable meals\n\n**Getting Around:**\n\nThe campus is walkable. Most buildings are within 5 minutes of each other.`,
      },
      {
        id: 'slide-3',
        tutorialId: 'mock-welcome-mendelu',
        order: 3,
        layout: 'two-column-wide-left',
        leftIcon: 'book-open',
        leftTitle: 'Study Tips',
        leftContent: `**Before the semester:**\n- Check your schedule in IS MENDELU\n- Register for exams early (they fill up fast!)\n- Join study groups on Facebook/Discord\n\n**During the semester:**\n- Attend all lectures - professors often hint at exam questions\n- Use reIS to track your materials and deadlines`,
        rightIcon: 'calendar',
        rightTitle: 'Key Dates',
        rightContent: `- **Week 1-2:** Course registration\n- **Week 6-7:** Mid-term tests\n- **Week 13:** Last lectures\n- **Exam period:** Check IS for dates`,
      },
    ],
  },
  {
    id: 'mock-erasmus-guide',
    associationId: 'esn',
    title: 'Erasmus+ Student Guide',
    description: 'Everything you need to know as an exchange student',
    isPublished: true,
    createdBy: 'admin@esn-mendelu.cz',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
    slides: [
      {
        id: 'erasmus-slide-1',
        tutorialId: 'mock-erasmus-guide',
        order: 1,
        layout: 'two-column',
        leftIcon: 'home',
        leftTitle: 'Accommodation',
        leftContent: `**University Dorms:**\n- Koleje - affordable student housing\n- Apply through international office\n- Shared rooms available\n\n**What to bring:**\n- Bedding is provided\n- Bring adapters for EU plugs`,
        rightIcon: 'wallet',
        rightTitle: 'Banking',
        rightContent: `**Czech Bank Account:**\n- Recommended: Fio Banka (free, English support)\n- Bring passport + visa/permit\n- Takes ~1 week to set up\n\n**Payments:**\n- Card payments widely accepted\n- Cash still useful for small shops`,
      },
    ],
  },
];
