# GitHub Sponsors Configuration
# Add your Buy Me a Coffee username below

buy_me_a_coffee: reis.mendelu

# You can also add other funding platforms here:
# github: [your-github-username]
# patreon: your-patreon-username
# ko_fi: your-ko-fi-username
