reviews:
  path_filters:
    - "!src/api/documents/parser.ts"
    - "!src/api/ukoly.ts"
    - "!src/api/osnovy.ts"
    - "!src/utils/parsers/**/*.ts"
  auto_review:
    enabled: true
    drafts: false
