import { readFileSync } from 'node:fs';
import { BEGIN, END } from './checklist';
import { buildBlock } from './checklist-cli';

// Part of the required Release gate: a test → main PR may not merge while the
// published privacy policy lags the repo, or while a generated privacy item is
// unticked. Run by release-gate.yml as `tsx scripts/privacy/gate.ts`, with the
// PR body in $PR_BODY; exits 1 with the reasons.

export const GIST_ID = 'e3007a015e24c210a017d21743f83784';

const norm = (s: string) => s.replace(/\r\n/g, '\n').replace(/\n$/, '');
export const sameContent = (a: string, b: string) => norm(a) === norm(b);

const itemsOf = (block: string, mark: RegExp): string[] =>
  block
    .split(/\r?\n/)
    .map((l) => mark.exec(l)?.[1]?.trim())
    .filter((x): x is string => Boolean(x));

/** Every checkbox item the generator produces for this release, ticked or not. */
export const expectedItems = (block: string) => itemsOf(block, /^\s*- \[[ xX]\]\s+(.*)$/);

/**
 * `expected` is regenerated by the gate itself from privacy/disclosures.ts at the
 * head SHA — never read from the PR body. A body the refresh has not rewritten
 * yet, or one someone deleted a line from, therefore cannot pass.
 */
export function gateFindings(i: {
  liveGist: string | null;
  gistReason?: string;
  repoPolicy: string;
  prBody: string;
  expected: string[];
}): string[] {
  const out: string[] = [];
  if (i.liveGist === null) {
    out.push(
      `Could not read the published policy gist ${GIST_ID}${i.gistReason ? ` (${i.gistReason})` : ''}; refusing to assume it is current.`
    );
  } else if (!sameContent(i.liveGist, i.repoPolicy)) {
    out.push(
      'The published privacy policy gist differs from docs/privacy-policy-app.md at this commit. Run `npm run privacy:publish`.'
    );
  }
  const b = i.prBody.indexOf(BEGIN);
  const e = i.prBody.indexOf(END);
  const ticked = new Set(
    b === -1 || e === -1 ? [] : itemsOf(i.prBody.slice(b, e), /^\s*- \[[xX]\]\s+(.*)$/)
  );
  for (const item of i.expected) {
    if (!ticked.has(item)) out.push(`Not ticked in the release PR: ${item}`);
  }
  return out;
}

export const GIST_OWNER = 'ElijaahInverted';
export const GIST_RAW_URL = `https://gist.githubusercontent.com/${GIST_OWNER}/${GIST_ID}/raw/privacy.md`;

/**
 * The published policy, read from the gist's raw URL — not the REST API. From an
 * Actions runner the API fails both ways: GITHUB_TOKEN (an App installation
 * token) is not accepted for gists, and without it the runner's shared IP hits
 * the anonymous rate limit and gets 403 (both seen on the 5.3.0 release PR).
 * The raw host is not rate-limited that way. Its CDN caches for 5 minutes; the
 * query string bypasses that, so a just-published policy is seen at once.
 */
export async function readLiveGist(
  fetchImpl: typeof fetch = fetch,
  now: () => number = Date.now
): Promise<{ content: string | null; reason?: string }> {
  try {
    const res = await fetchImpl(`${GIST_RAW_URL}?t=${now()}`);
    if (!res.ok) return { content: null, reason: `HTTP ${res.status}` };
    return { content: await res.text() };
  } catch (err) {
    return { content: null, reason: err instanceof Error ? err.message : String(err) };
  }
}

async function main(): Promise<void> {
  const gist = await readLiveGist();
  const block = await buildBlock(process.env.BASE_TAG ?? '', 'HEAD');
  const findings = gateFindings({
    liveGist: gist.content,
    gistReason: gist.reason,
    repoPolicy: readFileSync('docs/privacy-policy-app.md', 'utf-8'),
    prBody: process.env.PR_BODY ?? '',
    expected: expectedItems(block),
  });
  for (const f of findings) console.log(`::error::${f}`);
  if (findings.length) process.exit(1);
  console.log('Privacy disclosures: gist current, every item ticked.');
}

if (process.argv[1]?.endsWith('gate.ts')) await main();
