import { describe, it, expect } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  capacitorPluginDirs,
  readShippedAndroidPermissions,
  shippedAndroidPermissions,
} from '../androidPermissions';

const manifest = (body: string) =>
  `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
${body}
</manifest>`;

describe('shippedAndroidPermissions', () => {
  it('reads the app manifest uses-permission names without the android.permission. prefix', () => {
    const app = manifest(`
      <uses-permission android:name="android.permission.INTERNET" />
      <uses-permission-sdk-23 android:name="android.permission.CHANGE_WIFI_STATE"/>`);
    expect(shippedAndroidPermissions(app, [])).toEqual(['CHANGE_WIFI_STATE', 'INTERNET']);
  });

  it('adds what a plugin manifest merges in', () => {
    const app = manifest(`<uses-permission android:name="android.permission.INTERNET" />`);
    const plugin = manifest(`<uses-permission android:name="android.permission.WAKE_LOCK"/>`);
    expect(shippedAndroidPermissions(app, [plugin])).toEqual(['INTERNET', 'WAKE_LOCK']);
  });

  it('subtracts a plugin permission the app removes with tools:node="remove"', () => {
    const app = manifest(`
      <uses-permission android:name="android.permission.INTERNET" />
      <uses-permission
          android:name="android.permission.CAMERA"
          tools:node="remove" />`);
    const plugin = manifest(`<uses-permission android:name="android.permission.CAMERA"/>`);
    expect(shippedAndroidPermissions(app, [plugin])).toEqual(['INTERNET']);
  });

  it('ignores a permission that only guards a component (android:permission="…DUMP")', () => {
    const lib = manifest(`
      <application>
        <receiver android:name="x.ProfileInstallReceiver" android:permission="android.permission.DUMP" />
      </application>`);
    expect(shippedAndroidPermissions(manifest(''), [lib])).toEqual([]);
  });

  it('ignores a permission named only inside a comment', () => {
    const app = manifest(`
      <!-- SCHEDULE_EXACT_ALARM: <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" /> -->
      <uses-permission android:name="android.permission.INTERNET" />`);
    expect(shippedAndroidPermissions(app, [])).toEqual(['INTERNET']);
  });

  it('treats an unterminated comment as running to the end of the file', () => {
    const app = manifest(`
      <uses-permission android:name="android.permission.INTERNET" />
      <!-- <uses-permission android:name="android.permission.CAMERA" />`);
    expect(shippedAndroidPermissions(app, [])).toEqual(['INTERNET']);
  });

  it('keeps a non-android permission fully qualified', () => {
    const plugin = manifest(
      `<uses-permission android:name="com.google.android.gms.permission.AD_ID" />`
    );
    expect(shippedAndroidPermissions(manifest(''), [plugin])).toEqual([
      'com.google.android.gms.permission.AD_ID',
    ]);
  });
});

describe('capacitorPluginDirs', () => {
  it('lists every project dir in capacitor.settings.gradle, relative to android/', () => {
    const gradle = `// DO NOT EDIT THIS FILE!
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')

include ':capgo-capacitor-inappbrowser'
project(':capgo-capacitor-inappbrowser').projectDir = new File('../node_modules/@capgo/capacitor-inappbrowser/android')
`;
    expect(capacitorPluginDirs(gradle)).toEqual([
      '../node_modules/@capacitor/android/capacitor',
      '../node_modules/@capgo/capacitor-inappbrowser/android',
    ]);
  });
});

describe('readShippedAndroidPermissions', () => {
  it('follows an absolute projectDir, as cap sync sometimes writes one', () => {
    const root = mkdtempSync(join(tmpdir(), 'reis-perm-'));
    const plugin = join(root, 'elsewhere/plugin/android');
    mkdirSync(join(plugin, 'src/main'), { recursive: true });
    mkdirSync(join(root, 'android/app/src/main'), { recursive: true });
    writeFileSync(
      join(plugin, 'src/main/AndroidManifest.xml'),
      manifest(`<uses-permission android:name="android.permission.WAKE_LOCK"/>`)
    );
    writeFileSync(join(root, 'android/app/src/main/AndroidManifest.xml'), manifest(''));
    writeFileSync(
      join(root, 'android/capacitor.settings.gradle'),
      `project(':p').projectDir = new File('${plugin}')\n`
    );
    expect(readShippedAndroidPermissions(root)).toEqual(['WAKE_LOCK']);
  });

  it('throws rather than passing when a plugin manifest is missing', () => {
    const root = mkdtempSync(join(tmpdir(), 'reis-perm-'));
    mkdirSync(join(root, 'android/app/src/main'), { recursive: true });
    writeFileSync(join(root, 'android/app/src/main/AndroidManifest.xml'), manifest(''));
    writeFileSync(
      join(root, 'android/capacitor.settings.gradle'),
      `project(':p').projectDir = new File('../node_modules/missing/android')\n`
    );
    expect(() => readShippedAndroidPermissions(root)).toThrow(/Run npm ci/);
  });
});
