import L from 'leaflet';
import poiOutlinesJson from '../../data/map/poiOutlines.json';
import type { MapSelection } from '../../types/campusMap';
import { SELECTED_STYLE, ringToLatLng } from './mapHelpers';

/**
 * Footprints of the campus buildings the map has only a point for — D, J, L,
 * N, O, P, R, T, V. Choosing one (or a room in it: D05 → building D) used to
 * move the camera and draw nothing, so the student could not tell whether the
 * map was showing anything. The ways come from OpenStreetMap, which the map
 * already credits; `pois.json` is regenerated by reis-data, so they live here.
 */
interface PoiOutline {
  poiId: number;
  name: string;
  osmWay: number;
  ring: number[][];
}

export const POI_OUTLINES = new Map(
  (poiOutlinesJson as { outlines: PoiOutline[] }).outlines.map((o) => [o.poiId, o.ring])
);

/**
 * The footprint to highlight for this selection, or null. Only on the campus
 * overview: inside a floor plan the selected room is what is highlighted.
 */
export function outlineForSelection(
  sel: MapSelection | null,
  activeBuildingId: number | null
): number[][] | null {
  if (activeBuildingId !== null || sel?.kind !== 'poi') return null;
  return POI_OUTLINES.get(sel.poi.id) ?? null;
}

/**
 * Redraw the highlight: the selected-room orange, so "this is the one" reads the
 * same everywhere on the map. Not interactive — a tap on it must still reach
 * the basemap, which is what clears the selection.
 */
export function drawPoiHighlight(layer: L.LayerGroup, ring: number[][] | null): void {
  layer.clearLayers();
  if (ring) L.polygon(ringToLatLng(ring), { ...SELECTED_STYLE, interactive: false }).addTo(layer);
}
