/**
 * Regenerate the iOS launch image from `public/reIS_logo.svg`.
 *
 *   npm run gen:splash
 *
 * What it replaces: Capacitor's own scaffold splash — its blue chevron mark on
 * a white field — which had been shipping to the App Store since the app was
 * created. Reported as "opening reIS from app store shortly shows the white
 * screen with a capacitor logo instead of reIS". All three scale slots held
 * byte-identical copies of that same default.
 *
 * Generated by a script rather than dropped in as a binary, so the next person
 * can see where the image came from and re-run it when the mark changes. It
 * rasterises through Playwright, which this repo already installs and drives in
 * `scripts/shot.ts`; adding a dedicated rasteriser (sharp, resvg) for one asset
 * would be a dependency for a file that changes once a year.
 *
 * The mark's size is not a taste decision — see `lib/splashGeometry.ts`. The
 * storyboard aspect-FILLS this square, so the tallest phone magnifies the mark
 * the most while giving it the least room, and that device sets the size.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { chromium, type Page } from '@playwright/test';
import { IOS_DEVICES, markSizeForDevices, markFractionOnDevice } from './lib/splashGeometry';

/** Apple's launch-image square. Every scale slot uses the same source size. */
const CANVAS = 2732;

/** The mark's ceiling as a share of the shorter screen edge, on any device. */
const MAX_FRACTION = 0.34;

/**
 * The dark of the app icon and of the logo's own `--logo-bg`. Baked into the
 * image AND set on the storyboard's view, so the gap between the window
 * appearing and the image being laid out is not a white flash — which is the
 * half of the report that is about colour rather than about the logo.
 */
const BRAND_DARK = '#111827';

const OUT_DIR = resolve(process.cwd(), 'ios/App/App/Assets.xcassets/Splash.imageset');
const SLOTS = ['splash-2732x2732.png', 'splash-2732x2732-1.png', 'splash-2732x2732-2.png'];

const mark = markSizeForDevices(CANVAS, IOS_DEVICES, MAX_FRACTION);
const logo = readFileSync(resolve(process.cwd(), 'public/reIS_logo.svg'), 'utf8');

interface Ink {
  width: number;
  height: number;
  /** Signed distance from the canvas centre to the ink's centre, in px. */
  offX: number;
  offY: number;
}

/**
 * Find the box of every pixel that is not the background.
 *
 * Measured from the rendered PNG rather than taken from `getBBox()`, because
 * the two disagree and the pixels are what ships. `getBBox()` is geometric: it
 * ignores stroke, and the green dot carries a 4-unit stroke in `--logo-bg` —
 * invisible against this field, but it eats 2 units into the dot's left and
 * bottom. Trusting the geometric box put the mark 6px right and 5px high, which
 * is invisible in a thumbnail and wrong on a launch screen.
 */
async function measureInk(page: Page, png: Buffer): Promise<Ink> {
  const box = await page.evaluate(
    async (dataUrl: string) => {
      const img = new Image();
      img.src = dataUrl;
      await img.decode();
      const c = document.createElement('canvas');
      c.width = img.width;
      c.height = img.height;
      const ctx = c.getContext('2d')!;
      ctx.drawImage(img, 0, 0);
      const { data } = ctx.getImageData(0, 0, c.width, c.height);
      const bg = [data[0]!, data[1]!, data[2]!];
      let minX = c.width;
      let minY = c.height;
      let maxX = -1;
      let maxY = -1;
      for (let y = 0; y < c.height; y++) {
        for (let x = 0; x < c.width; x++) {
          const i = (y * c.width + x) * 4;
          // Generous, so an anti-aliased edge counts as ink.
          if (
            Math.abs(data[i]! - bg[0]!) > 12 ||
            Math.abs(data[i + 1]! - bg[1]!) > 12 ||
            Math.abs(data[i + 2]! - bg[2]!) > 12
          ) {
            if (x < minX) minX = x;
            if (x > maxX) maxX = x;
            if (y < minY) minY = y;
            if (y > maxY) maxY = y;
          }
        }
      }
      return { minX, minY, maxX, maxY, canvas: c.width };
    },
    `data:image/png;base64,${png.toString('base64')}`
  );

  return {
    width: box.maxX - box.minX + 1,
    height: box.maxY - box.minY + 1,
    offX: (box.minX + box.maxX + 1) / 2 - box.canvas / 2,
    offY: (box.minY + box.maxY + 1) / 2 - box.canvas / 2,
  };
}

const browser = await chromium.launch();
const page = await browser.newPage({
  viewport: { width: CANVAS, height: CANVAS },
  deviceScaleFactor: 1,
});

// The logo's rounded plate is `--logo-bg`, the same value as the field it sits
// on, so it is dropped rather than drawn: what is left is the mark itself,
// centred, which is what every iOS launch screen does and the only thing that
// survives being cropped on both axes.
await page.setContent(`
  <style>
    html, body { margin: 0; width: ${CANVAS}px; height: ${CANVAS}px; background: ${BRAND_DARK}; }
    body { display: grid; place-items: center; }
    svg { display: block; }
  </style>
  ${logo}
`);

/**
 * `reIS_logo.svg` is a favicon: a 128x128 rounded plate with the mark sitting
 * off-centre inside it — the R starts at x=45, the dot hangs below the baseline.
 * The plate was the centred thing, so dropping it leaves the mark neither
 * centred nor filling its box. Re-frame on the drawn content to get close.
 */
await page.evaluate(() => {
  const svg = document.querySelector('svg') as SVGSVGElement;
  svg.querySelector('.bg-shape')?.remove();
  const b = (svg as unknown as SVGGraphicsElement).getBBox();
  svg.setAttribute('viewBox', `${b.x} ${b.y} ${b.width} ${b.height}`);
  svg.setAttribute('preserveAspectRatio', 'xMidYMid meet');
});

const apply = (size: number, dx: number, dy: number) =>
  page.evaluate(
    ({ size, dx, dy }) => {
      const svg = document.querySelector('svg') as SVGSVGElement;
      svg.style.width = `${size}px`;
      svg.style.height = `${size}px`;
      svg.style.transform = `translate(${dx}px, ${dy}px)`;
    },
    { size, dx, dy }
  );

/**
 * Converge on "ink is `mark` px on its long edge and dead centre".
 *
 * A loop rather than arithmetic: the gap between the geometric box and the
 * inked box depends on stroke widths and anti-aliasing, so it is measured, not
 * modelled. It settles in two or three passes and the exit condition is the
 * same assertion that guards the write.
 */
let size = mark;
let dx = 0;
let dy = 0;
let png = await page.screenshot({ type: 'png' });
let ink = await measureInk(page, png);
let passes = 1;

for (; passes <= 8; passes++) {
  const longEdge = Math.max(ink.width, ink.height);
  if (Math.abs(ink.offX) <= 1 && Math.abs(ink.offY) <= 1 && Math.abs(longEdge - mark) <= 2) break;
  size *= mark / longEdge;
  dx -= ink.offX;
  dy -= ink.offY;
  await apply(size, dx, dy);
  png = await page.screenshot({ type: 'png' });
  ink = await measureInk(page, png);
}

await browser.close();

const longEdge = Math.max(ink.width, ink.height);
if (Math.abs(ink.offX) > 1 || Math.abs(ink.offY) > 1) {
  throw new Error(
    `launch image ink is off-centre by (${ink.offX}, ${ink.offY})px after ${passes} passes`
  );
}
if (Math.abs(longEdge - mark) > 2) {
  throw new Error(`launch image ink is ${longEdge}px on its long edge, expected ${mark}px`);
}

for (const slot of SLOTS) writeFileSync(resolve(OUT_DIR, slot), png);

console.log(`launch image: ${CANVAS}x${CANVAS}, mark ${mark}px on ${BRAND_DARK}`);
console.log(
  `  ink ${ink.width}x${ink.height}px, centred to (${ink.offX}, ${ink.offY})px after ${passes} pass(es)`
);
for (const d of IOS_DEVICES) {
  const pct = (markFractionOnDevice(CANVAS, mark, d) * 100).toFixed(1);
  console.log(`  ${d.label.padEnd(20)} mark is ${pct}% of the short edge`);
}
for (const slot of SLOTS) console.log(`  wrote ${resolve(OUT_DIR, slot)}`);
