/**
 * Pure logic for the one-way notes backup: render a subject's file-notes into
 * simple HTML (for Drive's HTML→Docs conversion), serialize them losslessly for
 * the restore sidecar, and hash the content for change detection. No I/O — easy
 * to test, easy to reason about. The orchestrator (driveNotesBackup.ts) performs
 * the actual Drive calls.
 *
 * Scope rule: we never use the Google Docs API (it needs the `documents` scope).
 * A real Doc is produced by uploading this HTML with the Docs target mimeType and
 * letting Drive convert it — so the markup stays deliberately simple.
 */

import { parseNote, type NoteCardData } from '../../components/SubjectFileDrawer/utils/noteParser';

/** One annotated file, as shipped from the iframe. `note` is the raw stored value. */
export interface FileNote {
    fileLink: string;
    fileName: string;
    /** Serialized note model (JSON {cards,notes}), or legacy format. Stored verbatim. */
    note: string;
}

export interface SubjectNotes {
    code: string;
    /** Drive folder name, mirrors the file backup: "BIK-DBS - Databases". */
    folderName: string;
    /** Stable Doc title — must not change across language switches (see plan). */
    title: string;
    files: FileNote[];
}

const BANNER = 'Generated by reIS from your file notes. Edits here are not saved back.';

function esc(s: string): string {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function withBreaks(s: string): string {
    return esc(s).replace(/\n/g, '<br>');
}

function cardToHtml(c: NoteCardData): string {
    const q = c.question.trim() ? `<p><b>${esc(c.question)}</b></p>` : '';
    const a = c.answer.trim() ? `<p>${withBreaks(c.answer)}</p>` : '';
    return q + a;
}

/** Render one subject's notes as simple HTML for Drive→Docs conversion. */
export function renderSubjectNotesHtml(subject: SubjectNotes): string {
    const parts: string[] = [`<h1>${esc(subject.title)}</h1>`, `<p><i>${esc(BANNER)}</i></p>`];
    for (const f of subject.files) {
        const data = parseNote(f.note);
        const cards = data.cards.filter((c) => c.question.trim() || c.answer.trim());
        const notes = data.notes.trim();
        if (!cards.length && !notes) continue;
        parts.push(`<h2>${esc(f.fileName)}</h2>`);
        for (const c of cards) parts.push(cardToHtml(c));
        if (notes) parts.push(`<p>${withBreaks(notes)}</p>`);
    }
    return `<html><body>${parts.join('')}</body></html>`;
}

/** Resolve a card image hash to raw base64 (no data: prefix), or null if missing. */
export type ImageBase64Lookup = (hash: string) => Promise<string | null>;

/** Like renderSubjectNotesHtml, but inlines card images as data:image/jpeg URIs.
 *  Runs in the iframe (which owns the image blobs). */
export async function renderSubjectNotesHtmlWithImages(
    subject: SubjectNotes,
    lookup: ImageBase64Lookup,
): Promise<string> {
    const parts: string[] = [`<h1>${esc(subject.title)}</h1>`, `<p><i>${esc(BANNER)}</i></p>`];
    for (const f of subject.files) {
        const data = parseNote(f.note);
        const cards = data.cards.filter((c) => c.question.trim() || c.answer.trim() || c.images.length);
        const notes = data.notes.trim();
        if (!cards.length && !notes) continue;
        parts.push(`<h2>${esc(f.fileName)}</h2>`);
        for (const c of cards) {
            parts.push(cardToHtml(c));
            for (const hash of c.images) {
                const b64 = await lookup(hash);
                if (b64) parts.push(`<p><img src="data:image/jpeg;base64,${b64}"></p>`);
            }
        }
        if (notes) parts.push(`<p>${withBreaks(notes)}</p>`);
    }
    return `<html><body>${parts.join('')}</body></html>`;
}

/** Body for a subject whose notes were all deleted — keeps the Doc, clears content. */
export function renderEmptyNotesHtml(): string {
    return `<html><body><p><i>${esc(BANNER)}</i></p></body></html>`;
}

/** Lossless empty sidecar for a subject with no notes (mirrors the drawer). */
export function serializeEmptyNotesJson(code: string): string {
    return serializeSubjectNotesJson({ code, folderName: '', title: '', files: [] });
}

/** Lossless JSON sidecar — the faithful restore source. Stores `note` verbatim. */
export function serializeSubjectNotesJson(subject: SubjectNotes): string {
    return JSON.stringify({
        schemaVersion: 1,
        code: subject.code,
        files: subject.files.map((f) => ({
            fileLink: f.fileLink,
            fileName: f.fileName,
            note: f.note,
        })),
    });
}

/** Stable 96-bit hex hash of the serialized notes — change signal + appProperties stamp value. */
export async function notesContentHash(json: string): Promise<string> {
    const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(json));
    return [...new Uint8Array(digest)]
        .slice(0, 12)
        .map((b) => b.toString(16).padStart(2, '0'))
        .join('');
}
