/**
 * Pure logic for the one-way notes backup: render a subject's file-notes into
 * simple HTML (for Drive's HTML→Docs conversion), serialize them losslessly for
 * the restore sidecar, and hash the content for change detection. No I/O — easy
 * to test, easy to reason about. The orchestrator (driveNotesBackup.ts) performs
 * the actual Drive calls.
 *
 * Scope rule: we never use the Google Docs API (it needs the `documents` scope).
 * A real Doc is produced by uploading this HTML with the Docs target mimeType and
 * letting Drive convert it — so the markup stays deliberately simple.
 */

import { parseNoteToBlocks, type NoteBlock } from '../../components/SubjectFileDrawer/utils/noteParser';

/** One annotated file, as shipped from the iframe. `note` is the raw stored value. */
export interface FileNote {
    fileLink: string;
    fileName: string;
    /** Serialized note blocks (JSON), or legacy plain text. Stored verbatim. */
    note: string;
}

export interface SubjectNotes {
    code: string;
    /** Drive folder name, mirrors the file backup: "BIK-DBS - Databases". */
    folderName: string;
    /** Stable Doc title — must not change across language switches (see plan). */
    title: string;
    files: FileNote[];
}

const BANNER = 'Generated by reIS from your file notes. Edits here are not saved back.';

function esc(s: string): string {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function withBreaks(s: string): string {
    return esc(s).replace(/\n/g, '<br>');
}

/** A block contributes nothing if all its text fields are blank. */
function isEmptyBlock(b: NoteBlock): boolean {
    if (b.type === 'toggle') return !(b.question || '').trim() && !(b.answer || '').trim();
    return !(b.content || '').trim();
}

function blockToHtml(b: NoteBlock): string {
    if (b.type === 'heading') {
        const tag = b.level === 1 ? 'h3' : b.level === 2 ? 'h4' : 'h5';
        return `<${tag}>${esc(b.content || '')}</${tag}>`;
    }
    if (b.type === 'toggle') {
        return `<p><b>${esc(b.question || '')}</b></p><p>${withBreaks(b.answer || '')}</p>`;
    }
    return `<p>${withBreaks(b.content || '')}</p>`;
}

/** Render one subject's notes as simple HTML for Drive→Docs conversion. */
export function renderSubjectNotesHtml(subject: SubjectNotes): string {
    const parts: string[] = [`<h1>${esc(subject.title)}</h1>`, `<p><i>${esc(BANNER)}</i></p>`];
    for (const f of subject.files) {
        const blocks = parseNoteToBlocks(f.note).filter((b) => !isEmptyBlock(b));
        if (!blocks.length) continue;
        parts.push(`<h2>${esc(f.fileName)}</h2>`);
        for (const b of blocks) parts.push(blockToHtml(b));
    }
    return `<html><body>${parts.join('')}</body></html>`;
}

/** Lossless JSON sidecar — the faithful restore source. Stores `note` verbatim. */
export function serializeSubjectNotesJson(subject: SubjectNotes): string {
    return JSON.stringify({
        schemaVersion: 1,
        code: subject.code,
        files: subject.files.map((f) => ({
            fileLink: f.fileLink,
            fileName: f.fileName,
            note: f.note,
        })),
    });
}

/** Stable 96-bit hex hash of the serialized notes — change signal + appProperties stamp value. */
export async function notesContentHash(json: string): Promise<string> {
    const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(json));
    return [...new Uint8Array(digest)]
        .slice(0, 12)
        .map((b) => b.toString(16).padStart(2, '0'))
        .join('');
}
